[font]
normal = { family = "Cascadia Mono" }
size = 10

[mouse]
hide_when_typing = true

[window]
dimensions = { columns = 180, lines = 60 }
opacity = 0.95

[general]
import = ["~/.config/alacritty/breeze.toml"]
