source 'https://rubygems.org'


gem 'rails', '4.2.5'
gem 'rails-api'
gem 'spring', :group => :development
gem 'sqlite3'
gem 'bcrypt', '~> 3.1.7'
gem 'active_model_serializers', '~> 0.9'
gem 'kaminari'

